# Your Name or Company
title: Jozef Chmelar
# Description of your website. This is used for social sharing.
description:  Jozef Chmelar | .

# A brief blurb about yourself
content: |+
  Do you know that there are people who think that software engineering is only about code? 
 
  I'm not one of them.

  Talk to people. Solve problems. Help others. Network. Keep business in mind. Iterate. Say no. Say yes. Trust.

  That's what I do. I do more. 
# Add your social links
social:
  - platform: medium
    url: https://medium.com/@Jozefchmelar
  - platform: github
    url: https://github.com/jozefchmelar
  - platform: twitter
    url: https://twitter.com/jojkooo
  - platform: linkedin
    url: https://www.linkedin.com/in/jozef-chmel%C3%A1r-92204728/

skills:
  - name : C#
  - name : Kotlin
  - name : Android
  - name : JavaScript
  - name : RxJava
interests:
  - name : Startups
  - name : Soft-skills
  - name : Functional programming
  - name : Marketing
  - name : Business development

# General settings
url: https://jozef.chmelar.tech/
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-139370409-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
