# Your Name or Company
title: Jozef Chmelar
# Description of your website. This is used for social sharing.
description: Wakeboarding 🏄 Skiing ⛷️ and 3AM talks with friends about the purpose of life. And programmer but who cares.

# A brief blurb about yourself
content: In the end, happiness is a side effect of living well.
# Add your social links
social:
  - platform: medium
    url: https://medium.com/@Jozefchmelar
  - platform: github
    url: https://github.com/jozefchmelar
  - platform: twitter
    url: https://twitter.com/jojkooo
  - platform: linkedin
    url: https://www.linkedin.com/in/jozefchmelar
    
skills:
  - name : C#
  - name : Kotlin
  - name : Android
  - name : JavaScript
  - name : RxJava
  - name : CI/CD
  
interests:
  - name : Featured in C# Digest newsletter
    url : https://csharpdigest.net/digests/287
  - name : Featured in dotNET Weekly newsletter
    url : http://dnw-newsletter.azurewebsites.net/issues/2019/49/
  - name : Startup weekend Zilina 2018 - 2nd place
    url : https://www.linkedin.com/posts/jozef-chmel%C3%A1r-92204728_startupweekend-swza-activity-6462584494540095488-0DYl
  - name : Accenture Panel story Award
    url : https://www.linkedin.com/posts/jozef-chmel%C3%A1r-92204728_we-won-an-award-with-our-project-about-augmented-activity-6374187385042849792-QZtV
  - name : Google Fundamentals of digital marketing
    url : https://www.linkedin.com/posts/jozef-chmel%C3%A1r-92204728_fundamental-of-digital-marketing-activity-6528224904381370368-79Xf  
  - name : Pluralsight C# Expert
    url : https://www.linkedin.com/posts/jozef-chmel%C3%A1r-92204728_measure-your-skills-activity-6602219741249585152-SZr-  
  - name : Erasmus - Jyväskylän ammattikorkeakoulu
    url : https://www.jamk.fi/en/Home/ 
  - name : Read my articles
    url : https://medium.com/@Jozefchmelar

# General settings
url: https://jozef.chmelar.tech/
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-139370409-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
